const { copyElectronRuntimeLicenses } = require("./scripts/copy-electron-runtime-licenses.cjs");

const commonFiles = [
  "apps/desktop/dist/**/*",
  "apps/desktop/assets/**/*",
  "dist-renderer/**/*",
  "packages/contracts/dist/**/*",
  "packages/contracts/package.json",
  "packages/domain/dist/**/*",
  "packages/domain/package.json",
  "packages/agentcore-adapter/dist/**/*",
  "packages/agentcore-adapter/package.json",
  "packages/pfsaa-host/dist/**/*",
  "packages/pfsaa-host/package.json",
  "packages/permission-engine/dist/**/*",
  "packages/permission-engine/package.json",
  "packages/i18n/dist/**/*",
  "packages/i18n/package.json",
  "packages/ui-system/dist/**/*",
  "packages/ui-system/package.json",
  "package.json",
  "LICENSE",
  "LICENSE.upstream-MIT",
  "NOTICE",
  "THIRD_PARTY_NOTICES.txt",
  "!.claude/**/*",
  "!.codex/**/*",
  "!.pi/**/*",
  "!.playwright-cli/**/*",
  "!.workbuddy/**/*",
  "!apps/desktop/src/**/*",
  "!apps/desktop/scripts/**/*",
  "!apps/desktop/native/**/*",
  "!apps/desktop/public/**/*",
  "!packages/*/src/**/*",
  "!node_modules/@pfsaa/*/src/**/*",
  "!node_modules/@pfsaa/*/tsconfig.json",
  "!node_modules/@oxc-project/**/*",
  "!node_modules/@rolldown/**/*",
  "!node_modules/@vitejs/**/*",
  "!node_modules/electron/**/*",
  "!node_modules/lightningcss/**/*",
  "!node_modules/lightningcss-*/**/*",
  "!node_modules/rolldown/**/*",
  "!node_modules/vite/**/*",
  "!docs/**/*",
  "!rules/**/*",
  "!AGENTS.md",
  "!CLAUDE.md",
  "!CONTRIBUTING.md",
  "!README*.md",
  "!SECURITY.md",
  "!**/*.map",
  "!**/*.d.ts",
  "!**/*.d.mts",
  "!**/*.d.cts",
  "!**/*.tsbuildinfo",
  "!node_modules/**/tree-sitter-bash/src/**",
  "!node_modules/**/tree-sitter-bash/grammar.js",
];

const macSigningConfigured = Boolean(process.env.CSC_LINK || process.env.CSC_NAME);
const macNotarizationConfigured = Boolean(
  process.env.APPLE_API_KEY
  && process.env.APPLE_API_KEY_ID
  && process.env.APPLE_API_ISSUER,
);

module.exports = {
  appId: "com.pfsaa.desktop",
  productName: "PFSAA",
  directories: { output: "release" },
  forceCodeSigning: process.env.PFSAA_FORCE_CODE_SIGNING === "true" || process.env.PIDECK_FORCE_CODE_SIGNING === "true",
  asar: true,
  asarUnpack: ["**/*.node", "apps/desktop/assets/**/*"],
  npmRebuild: false,
  files: commonFiles,
  afterExtract: copyElectronRuntimeLicenses,
  win: {
    target: { target: "nsis", arch: ["x64"] },
    artifactName: "${productName}-${version}-windows-${arch}-setup.${ext}",
    icon: "apps/desktop/assets/pfsaa-icon.ico",
    files: [
      ...commonFiles,
      "!node_modules/**/@mariozechner/clipboard-{darwin,linux}*/**",
      "!node_modules/**/@mariozechner/clipboard-win32-arm64-msvc/**",
      "!node_modules/**/prebuilds/{darwin,linux}-*/**",
      "!node_modules/**/prebuilds/win32-arm64/**",
      "!node_modules/**/native/{darwin,linux}/**",
      "!node_modules/**/native/win32/prebuilds/win32-arm64/**",
    ],
  },
  nsis: {
    oneClick: false,
    perMachine: false,
    allowToChangeInstallationDirectory: true,
  },
  mac: {
    target: ["dmg"],
    artifactName: "${productName}-${version}-macos-${arch}.${ext}",
    icon: "apps/desktop/assets/pfsaa-icon.png",
    category: "public.app-category.developer-tools",
    minimumSystemVersion: "12.0",
    hardenedRuntime: macSigningConfigured,
    ...(macSigningConfigured ? {} : { identity: null }),
    ...(macSigningConfigured ? {
      entitlements: "apps/desktop/entitlements.mac.plist",
      entitlementsInherit: "apps/desktop/entitlements.mac.plist",
    } : {}),
    ...(macSigningConfigured && macNotarizationConfigured ? { notarize: true } : {}),
    files: [
      ...commonFiles,
      "!node_modules/**/@mariozechner/clipboard-{win32,linux}*/**",
      "!node_modules/**/prebuilds/{win32,linux}-*/**",
      "!node_modules/**/native/{win32,linux}/**",
    ],
  },
  dmg: { title: "PFSAA" },
};
